replicaCount: 3

image:
  repository: princemitnick/web-nginx
  tag: v1
  pullPolicy: ifNotPresent

service:
  type: LoadBalancer
  port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
    initialDelaySeconds: 3
    periodSeconds: 5