apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/princemitnick/web-nginx-project.git   # remplace ton repo ici
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true